name: Build & Publish
uses: ashutoshvarma/action-cmake-build@master
with:
  build-dir: ${{ runner.workspace }}/build # will set the CC & CXX for cmake
  cc: gcc
  cxx: g++
  build-type: Release # Extra options pass to cmake while configuring project
  configure-options: -DCMAKE_C_FLAGS=-w32 -DPNG_INCLUDE=OFF
  run-test: true
  ctest-options: -R mytest # install the build using cmake --install
  install-build: true # run build using '-j [parallel]' to use multiple threads to build
  parallel: 14
- uses: actions/upload-artifact@v3
  with:
    name: ps3dec
    path: ${{ runner.workspace }}/build/ps3dec
