name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-i686-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            git
            make
            mingw-w64-i686-toolchain
            mingw-w64-i686-SDL2
            mingw-w64-i686-zlib
            mingw-w64-i686-gcc
            mingw-w64-x86_64-gcc
            mingw-w64-i686-glew
            mingw-w64-x86_64-glew
            mingw-w64-i686-SDL2
            mingw-w64-i686-SDL
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL
            mingw-w64-x86_64-mbedtls
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            python3
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build ps3dec
        run: cmake
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sm64ex-windows
          path: D:\a\PS3Dec\PS3Dec\build\
          retention-days: 0
