name: Compile C App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libmbedtls-dev

      - name: Compile for Linux
        run: gcc -o PS3Dec PS3Dec.c -lmbedtls -fopenmp

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-executable
          path: PS3dec

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile for Windows
        run: |
          mkdir build && cd build
          vcpkg install mbedtls
          cmake .. && cmake --build ..

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: PS3Dec.exe
