name: Compile C App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libmbedtls-dev

      - name: Compile for Linux
        run: |
          mkdir build && cd build
          cmake .. && make

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-executable
          path: ./build/Release/

      - name: Upload Linux Releases
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./build/Release/
          draft: false


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Compile for Windows
        run: |
          mkdir build && cd build
          vcpkg install mbedtls
          vcpkg integrate install
          cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .. && msbuild PS3Dec.sln

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: .


      - name: Upload Releases 
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.exe"
          draft: false
