name: Compile C App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libmbedtls-dev

      - name: Compile for Linux
        run: |
          mkdir build && cd build
          cmake .. && make

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-executable
          path: .

      - name: Create Linux Release
        id: create_linux_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-linux
          release_name: Linux Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ./build/*


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Compile for Windows
        run: |
          mkdir build && cd build
          vcpkg install mbedtls
          vcpkg integrate install
          cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .. && msbuild PS3Dec.sln

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: .

      - name: Create Windows Release
        id: create_windows_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-windows
          release_name: Windows Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ./build/*
